concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}
jobs:
  build:
    name: BUILD ${{ github.sha }}
    needs:
    - testing
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up python 3
      uses: actions/setup-python@v5
      with:
        architecture: x64
        python-version: 3.x
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      name: Build with Ant
      run: ant artifact
      working-directory: ./framework
    - continue-on-error: true
      name: ziping artifact
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: play-${{ github.sha }}
        path: './framework/dist/*

          '
  testing:
    name: Check / Tests -> JDK-${{ matrix.jdk }}/${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up python 3
      uses: actions/setup-python@v5
      with:
        architecture: x64
        cache: pip
        cache-dependency-path: '**/requirements.txt'
        python-version: 3.x
    - continue-on-error: true
      run: pip install -r python/requirements.txt
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Build with Ant
      run: ant test
      working-directory: ./framework
    strategy:
      matrix:
        exclude:
        - jdk: 11
          os: windows-latest
        jdk:
        - 11
        - 17
        os:
        - ubuntu-latest
        - windows-latest
name: Check
on:
  repository_dispatch:
    types: trigger-ga___build-test.yml
