concurrency:
  cancel-in-progress: true
  group: delete-caches
jobs:
  delete-public-local-caches:
    name: Delete unneeded caches
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "gh cache list --limit 500 --order asc --sort last_accessed_at | grep 'play-published-local'\
        \ > caches.txt || true\necho \"Found $(wc -l < caches.txt | xargs) published\
        \ local cache entries\"\n\ncurrent_time=$(date -u +%s)\nexpiration_time=$((current_time\
        \ - 7200)) # 2 hour ago\n\necho \"Current time is $(date -d @$current_time)\"\
        \necho \"All entries hadn't been use from $(date -d @$expiration_time) will\
        \ be delete\"\n\nwhile IFS=$'\\t' read -r id name size created_at last_accessed_at;\
        \ do\n  accessedTimestamp=$(date -u -d \"$last_accessed_at\" +%s)\n  # Uncomment\
        \ to check on Mac OS \n  # accessedTimestamp=$(date -j -f \"%Y-%m-%dT%H:%M:%SZ\"\
        \ \"$last_accessed_at\" +%s)\n  if [ \"$accessedTimestamp\" -lt \"$expiration_time\"\
        \ ]; then\n    echo \"Delete $id $name ($last_accessed_at)\"\n    gh cache\
        \ delete $id\n  fi\ndone < caches.txt\nrm -rf caches.txt\n"
name: Delete Caches
on:
  repository_dispatch:
    types: trigger-ga___delete-caches.yml
permissions:
  actions: write
