jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@v6
      with:
        commitish: ${{ env.GITHUB_REF_NAME }}
        config-name: release-drafts/increasing-minor-version.yml
        name: Play $RESOLVED_VERSION
name: Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___release-drafter.yml
permissions: {}
